spring:
  datasource:
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/db1
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver

    db2:
      jdbc-url: jdbc:mysql://localhost:3306/db2
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath*:/mapper/*.xml